// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSO1tFe0DijHszoGyfMR3-y8ZtqLrH3Xk',
    appId: '1:896217504035:web:d5860919fe2dae98f71496',
    messagingSenderId: '896217504035',
    projectId: 'career-3837e',
    authDomain: 'career-3837e.firebaseapp.com',
    storageBucket: 'career-3837e.firebasestorage.app',
    measurementId: 'G-YJWVDEENF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXdxCCfu6Txo5FrnNCiIfT8KWYw_XweWk',
    appId: '1:896217504035:android:166555af2e6d010cf71496',
    messagingSenderId: '896217504035',
    projectId: 'career-3837e',
    storageBucket: 'career-3837e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYUCu7rStG5U8yB5cXH7uRCaCo-Vzhtck',
    appId: '1:896217504035:ios:5686c37e14ccef5df71496',
    messagingSenderId: '896217504035',
    projectId: 'career-3837e',
    storageBucket: 'career-3837e.firebasestorage.app',
    iosBundleId: 'com.almahd.career',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYUCu7rStG5U8yB5cXH7uRCaCo-Vzhtck',
    appId: '1:896217504035:ios:5686c37e14ccef5df71496',
    messagingSenderId: '896217504035',
    projectId: 'career-3837e',
    storageBucket: 'career-3837e.firebasestorage.app',
    iosBundleId: 'com.almahd.career',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSO1tFe0DijHszoGyfMR3-y8ZtqLrH3Xk',
    appId: '1:896217504035:web:334b4d97b3006a9af71496',
    messagingSenderId: '896217504035',
    projectId: 'career-3837e',
    authDomain: 'career-3837e.firebaseapp.com',
    storageBucket: 'career-3837e.firebasestorage.app',
    measurementId: 'G-56J53R16JR',
  );
}
